# Clean data

#### Load data

In [7]:
import pandas as pd

df = pd.read_csv("./data/playlist_stats.csv")

In [8]:
from notebook_functions import show

show(df)

,name,artist,album,added_by,added_at
0,Rumble,"Skrillex, Fred again.., Flowdan",Rumble,Thomas Brouwer,2023-01-09T10:23:07Z
1,Strung Out Johnny,Iggy Pop,EVERY LOSER,hvdpal58,2023-01-09T20:40:04Z
2,Kill Bill,SZA,SOS,hvdpal58,2023-01-09T20:50:12Z
3,Sail On By,Blanco White,Sail On By,svdpal,2023-01-13T12:15:11Z
4,Be On Your Way,Daughter,Be On Your Way,svdpal,2023-01-13T12:19:16Z
...,...,...,...,...,...
219,Feelings (feat. J Hus),"Jorja Smith, J Hus",falling or flying,hvdpal58,2023-12-06T11:21:06Z
220,GO GO GO,Jorja Smith,falling or flying,hvdpal58,2023-12-06T11:29:02Z
221,Alsof Het Weer Gister Is,S10,Mis,Joline Charlotte,2023-12-08T17:01:02Z
222,namesake,Noname,Sundial,Thomas Brouwer,2023-12-09T21:04:27Z
223,leavemealone,"Fred again.., Baby Keem",leavemealone,Joline Charlotte,2023-12-10T12:50:35Z

#### Rename columns

In [9]:
# Rename added_by columns
df.loc[df["added_by"] == "svdpal", "added_by"] = "Sandra"
df.loc[df["added_by"] == "hvdpal58", "added_by"] = "Hans"
df.loc[df["added_by"] == "Joline Charlotte", "added_by"] = "Joline"
df.loc[df["added_by"] == "Thomas Brouwer", "added_by"] = "Thomas"

#### Drop duplicates

Based on `name` and `artist` columns.

In [10]:
# Count rows per name and artist
df_duplicates = df.groupby(["name", "artist"]).size().reset_index(name="counts")
df_duplicates = df_duplicates.sort_values(by="counts", ascending=False)
# filter where counts > 1
df_duplicates = df_duplicates[df_duplicates["counts"] > 1]

# locate duplicates in original dataframe
duplicates = df[df.duplicated(subset=["name", "artist"], keep=False)].sort_values(
    by=["name", "artist"]
)
show(duplicates, 10)

,name,artist,album,added_by,added_at
4,Be On Your Way,Daughter,Be On Your Way,Sandra,2023-01-13T12:19:16Z
34,Be On Your Way,Daughter,Swim Back,Sandra,2023-03-17T11:33:48Z
188,Houdini,Dua Lipa,Houdini,Sandra,2023-11-10T12:21:16Z
193,Houdini,Dua Lipa,Houdini,Joline,2023-11-16T07:38:13Z
214,Mis,S10,Mis,Joline,2023-11-26T14:51:04Z
217,Mis,S10,Mis,Thomas,2023-11-27T20:22:44Z
30,Not Worth It,Maria Mena,Not Worth It,Sandra,2023-03-12T05:29:47Z
147,Not Worth It,Maria Mena,And Then Came You,Joline,2023-09-15T06:24:00Z
105,Sliver of Ice,"ANOHNI, Antony and the Johnsons",Sliver of Ice,Thomas,2023-06-22T06:49:19Z
128,Sliver of Ice,"ANOHNI, Antony and the Johnsons",My Back Was A Bridge For You To Cross,Thomas,2023-07-27T17:17:21Z

In [11]:
# remove duplicates and keep first occurence
df = df.drop_duplicates(subset=["name", "artist"], keep="first")

#### Export to csv

In [12]:
# save to csv
df.to_csv("./data/playlist_stats_clean.csv", index=False)